# Generated by Django 5.0.6 on 2024-07-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd_dynamic_advisories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyme_asesor',
            name='fecha_contratacion',
            field=models.DateField(null=True),
        ),
    ]
